version: 2

jobs:
  coditsu:
    machine: true
    steps:
      - checkout
      - run: \curl -sSL https://api.coditsu.io/run/ci | bash

  specs:
    docker:
      - image: circleci/ruby:2.7.1-node-browsers
    steps:
      - restore_cache:
          keys:
            - v{{ .Environment.CIRCLE_CACHE_VERSION }}-git-{{ .Branch }}-{{ .Revision }}
            - v{{ .Environment.CIRCLE_CACHE_VERSION }}-git-{{ .Branch }}-
            - v{{ .Environment.CIRCLE_CACHE_VERSION }}-git-
      - checkout
      - save_cache:
          key: v{{ .Environment.CIRCLE_CACHE_VERSION }}-git-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".git"
      - restore_cache:
          keys:
            - v{{ .Environment.CIRCLE_CACHE_VERSION }}-{{arch}}-gem-lock-{{ checksum "Gemfile.lock" }}
            - v{{ .Environment.CIRCLE_CACHE_VERSION }}-{{arch}}-gem-lock-
      - run: |
          git config --global user.email "ci@coditsu.io"
          git config --global user.name "Coditsu CI"
          sudo rm -rf /usr/local/bin/bundle && gem install bundler
          bundle update --bundler
          yes | gem update --system || true
          bundle config github.https true
          bundle check --path=vendor/bundle || bundle install --path vendor/bundle
      - save_cache:
          key: v{{ .Environment.CIRCLE_CACHE_VERSION }}-{{arch}}-gem-lock-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run: bundle exec rspec

workflows:
  version: 2
  build:
    jobs:
      - coditsu
      - specs

  nightly:
    triggers:
      - schedule:
          cron: '0 0 * * *'
          filters:
            branches:
              only:
                - master
    jobs:
      - coditsu
      - specs
